### ISSUE TITLE
Error: The system cannot find the file specified.

### ISSUE THREAD

**Issue by ojvribeiro** [TristanMouchet/laravel-mix-simple-image-processing#6]
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: The system cannot find the file specified.

    at notFoundError (C:\...\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\...\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\...\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\...\\node_modules\\jpegtran-bin\\vendor\\jpegtran.exe',
  killed: false,
  stdout: '',
  stderr: 'The system cannot find the file specified.\r\n',
  failed: true,
  signal: null,
  cmd: 'C:\\...\\node_modules\\jpegtran-bin\\vendor\\jpegtran.exe -copy none -optimize -outfile C:\\...\\AppData\\Local\\Temp\\47a6...eacacde C:\\...\\AppData\\Local\\Temp\\b98e049a-...14dcf0b',
  timedOut: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

----

For anyone facing this error, install the following package:

```
npm install -D imagemin-jpegtran
```

For some reason the `laravel-mix-simple-image-processing`'s dependency is not working.

**Comment by TristanMouchet** [comment]
Thank you for reporting the issue and providing a solution to it!

I didn't run into this one and I don't seem to be able to reproduce it so I will just close it for now. 👍
